fix: do not drop null Vecs
filecoin-project/rust-fil-ffi-toolkit pull request #11
Opened 2022-03-18 19:10 UTC by dignifiedquire

Closes #8

2022-03-18 21:00 UTC, Stebalien approved these changes

2022-03-21 13:41 UTC, vmx requested changes

2022-03-21 13:41 UTC, vmx commented on drop-struct-macro-derive/src/lib.rs
> +    // Only take *mut pointers into account (also not *mut)
I guess that should then say "also not ***const**".

2022-03-23 09:21 UTC, dignifiedquire commented
closing, moving to a world where filecoin-ffi doesn't use this crate anymore

2022-03-23 09:21 UTC, closed without merging